spatie/laravel-db-snapshots

src/SnapshotFactory.php

This PR sanitizes the given snapshot (file)name so it doesn't create subdirectories.
If the user enters a path as a snapshot name the snapshot is created at the given path on the disk.
It seems cleaner to have all snapshots in the root directory of the disk tho. This avoids confusion when having multiple snapshots with the same name in different subdirectories:

Sanitize snapshot (file)name

---

src/Commands/Create.php

I believe this is a typo. without `=` no option can be passed

missing equal in connection parameter

---

src/Commands/Create.php
tests/Commands/CreateTest.php

We use Bash on Windows internally for development, which uses the Windows filesystem. Windows does not support `:` in filenames unfortunately 😢. Creating a snapshot with the default name results in the following error:
```
$ mysqldump --defaults-extra-file="/tmp/credentials" --skip-comments --extended-insert --result-file="2017-09-25 15:16:33.sql" database
mysqldump: Can't create/write to file '2017-09-25-15:16:33.sql' (Errcode: 22 - Invalid argument)
```
With this fix, success!
```
$ mysqldump --defaults-extra-file="/tmp/credentials" --skip-comments --extended-insert --result-file="2017-09-25_15-16-33.sql" database
```

Use dashes in default snapshot name to support Windows

---

src/Commands/Delete.php

If one calls the `snapshot:delete` command without providing a snapshot name and if there is no available snapshot, a `\LogicException` will be thrown when trying to build a list of choices.
This PR guards against the exception in a similar way to what is done within the [`snapshot:list`](https://github.com/spatie/laravel-db-snapshots/blob/bd4f67c6636e819b86fe3af40c9ce23417115265/src/Commands/ListSnapshots.php#L18-L24) and [`snapshot:load`](https://github.com/spatie/laravel-db-snapshots/blob/bd4f67c6636e819b86fe3af40c9ce23417115265/src/Commands/Load.php#L21-L27) commands.

Prevent Exception when trying to delete snapshots when there are none

---

README.md
composer.json
config/db-snapshots.php
src/Commands/Create.php
src/Snapshot.php
src/SnapshotFactory.php
src/SnapshotRepository.php
tests/Commands/CreateTest.php
tests/Commands/LoadTest.php
tests/SnapshotRepositoryTest.php
tests/TestCase.php

This adds support to `laravel-db-snapshots` to make it support creating gzipped snapshots either by passing the command line option or configuring it via the config file.  `spatie/db-dumper` already supports this feature, and this allows the snapshot tool to expose that feature.  Fairly straight forward cli usage:
```console
$ artisan snapshot:create mysnap --compress
$ artisan snapshot:load mysnap
```
Note: on my machine with the dependencies listed for this project, dumping sqlite databases appears to include `IF NOT EXISTS` which the current tests do not account for. I did not research where the change happened to make the current tests fail, but I did fix it none-the-less (see `tests/Commands/CreateTest.php`).
This is actually 1 part of a 2 part feature, I would like to be able to (at …

Feature: support creating and loading gzip snapshots

---

src/Commands/Create.php
tests/Commands/CreateTest.php

The current implementation [passes a second parameter into `option`](https://github.com/spatie/laravel-db-snapshots/blob/master/src/Commands/Create.php#L26) seemingly as a default to fallback to if no option is passed, but this is [not a feature of the `option` method](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Console/Command.php#L304).
This call returns `false` if the `--compress` option is not present, which then causes the ternary to always pass in `false` instead of falling back to the value in the config as it strictly checks against `null`

Fix compression option from config not being respected

---

src/Commands/Load.php

I found an issue where the load command will not work when APP_ENV is set to 'production'. As the command uses the ConfirmableTrait, it must also define a "--force" option in the command signature. Without the force option, the command outputs an error saying "The force option does not exist".
Simply adding the option to the signature fixes both the confirmation dialog AND the --force option usage.
Thanks!

Load command does not work in production env

---

src/SnapshotFactory.php

This issue has been documented several times in other respositories but was never actually fixed. Most notably here:
https://github.com/spatie/laravel-backup/issues/393
The problem may need to be fixed in multiple repositories.
Essentially, when calling the TemporaryDirectory->delete() method, if you also call an fclose() before php has had adequate time to complete its garbage collection cycles, the resources that were fclosed only appear to be fclosed, and are in fact still reserved by php.
By forcing a php garbage collection cycle using gc_collect_cycles() we can ensure that the rmdir function called in spatie/temporary-directory/TemporaryDirectory does not fail due to files still being reserved in memory (in the garbage due to fclose, but reserved nonetheless).
Replicating this issue …

Fixes an obscure but repeatable issue relating to rmdir failing

---

README.md
src/Commands/Cleanup.php
src/DbSnapshotsServiceProvider.php
tests/Commands/CleanupTest.php

This adds a command to cleanup old snapshots. It accepts a --keep option which specifies how many snapshots to keep and deletes the rest. 
Example: I have an app that is scheduled to create a snapshot twice a day. This command could run to keep the snapshot directory from having too many snapshots.

Add command to cleanup old snapshots

---

README.md
src/Commands/Load.php
tests/Commands/LoadTest.php

I took this approach instead of the initial suggestion in https://github.com/spatie/laravel-db-snapshots/issues/94 as the intent of the option is much clearer

Add a --latest option to the snapshots:load method to load the latest available snapshot

---

src/Exceptions/CannotCreateDisk.php

This closes https://github.com/spatie/laravel-db-snapshots/issues/88
Since PHP 7.4, passing in the glue string as the second argument is deprecated and will throw an error. [Ref](https://www.php.net/manual/en/migration74.deprecated.php)

Fix deprecated implode usage

---

src/Commands/Cleanup.php
tests/Commands/CleanupTest.php

In #79, support for cleaning up old snapshots was added, keeping a specified number of snapshots. I am using this package for E2E tests, and want to clean up ALL snapshots at once. However, a bug in the logic considers `--keep=0` to be the same as the `--keep` option being absent. This PR fixes that and adds more tests for the behaviour of the keep flag.

Fix cleaning up all snapshots

---

src/Commands/Load.php
tests/TestCase.php

I already created a PR but is was rejected because failing tests. Unfortunately the original test seems to be wrong. The autogenerated snapshots are created nano seconds after each other so the createdAt() function returns always the same timestamp. To fix this I had to add a one second gap before the latest snapshot is created, this slows the tests a bit.

Fix getting latest snapshot and update test

---

README.md

Added note on how to pass options to the underlying db-dumper, as it took me a while to figure it out. Hope it helps others!
Also fixed minor issue w/ reference to `database.php` (was `databaseS.php`)

added extra options

---

.editorconfig
.gitattributes
.github/FUNDING.yml
.github/SECURITY.md
.github/workflows/run-tests.yml
.gitignore
.php_cs.dist
CHANGELOG.md
README.md
composer.json
phpunit.xml.dist
src/Commands/Cleanup.php
src/Commands/Concerns/AsksForSnapshotName.php
src/Commands/Create.php
src/Commands/Delete.php
src/DbDumperFactory.php
src/DbSnapshotsServiceProvider.php
src/Events/CreatedSnapshot.php
src/Events/CreatingSnapshot.php
src/Events/DeletedSnapshot.php
src/Events/DeletingSnapshot.php
src/Events/LoadedSnapshot.php
src/Events/LoadingSnapshot.php
src/Exceptions/CannotCreateDbDumper.php
src/Exceptions/CannotCreateDisk.php
src/Snapshot.php
src/SnapshotFactory.php
src/SnapshotRepository.php

This PR adds a new major version, v2.0.0.
Specifically, it:
- Removes support for all PHP 7.x versions.
- Requires PHP 8.0+.
- Uses PHP 8 syntax where possible.
- Removes unnecessary PHP docblocks per Spatie's guidelines.
- Removes Laravel v6 support.
- Implements `spatie/laravel-package-tools`.
- Uses the latest PHP 8 version of spatie packages where possible.
- Adds/updates various dot/config files from `spatie/package-skeleton-laravel`.
- Adds a note to the readme on what package version to use for Laravel 6 or PHP 7.
- _Updates the changelog - release date needs to be updated, currently is "unreleased"._

Add PHP 8-only Support (v2)

---

src/SnapshotRepository.php

Simple fix for #117 — don't try to access `extension` of file's `pathinfo` unless it exists

Fix undefined array key error in `SnapshotRepository::getAll()`

---

README.md
composer.json
config/db-snapshots.php
src/Commands/Create.php
src/Events/CreatingSnapshot.php
src/SnapshotFactory.php
tests/Commands/CreateTest.php
tests/Events/CreatingSnapshotTest.php
tests/TestCase.php

with this PR users can exclude tables that they want instead of passing each table name in `--table` option.

add --exclude to the create command

---

src/DbDumperFactory.php
tests/DbDumperFactoryTest.php

[PostgreSQL](https://www.postgresql.org/) users often use a connection pool like [PgBouncer](https://www.pgbouncer.org/).
This requires a `connect_via_database` database config to work properly.
Laravel added support for this: https://github.com/illuminate/database/commit/459df89ff6799c5bbcf2bfd0c56159abcebc33dd
This merge request adds support for the optional `connect_via_database` config setting.

Support connect_via_database

---

src/DbDumperFactory.php

This should solve:
```
local.ERROR: Cannot create a dumper for db driver `mariadb`. Use `mysql`, `pgsql` or `sqlite`. {"exception":"[object] (Spatie\\DbSnapshots\\Exceptions\\CannotCreateDbDumper(code: 0): Cannot create a dumper for db driver `mariadb`. Use `mysql`, `pgsql` or `sqlite`. at /app/vendor/spatie/laravel-db-snapshots/src/Exceptions/CannotCreateDbDumper.php:11)
```
Since Laravel 11, MariaDB has a dedicated driver.

Add MariaDB support

---

README.md
src/Commands/Create.php
tests/Commands/CreateTest.php

If you don't pass a name, but DO pass a connection, this will prepend the connection onto the name. Example output below

Prepend the connection onto the name

---

.github/workflows/run-tests.yml
composer.json
src/Commands/Cleanup.php
src/Exceptions/CannotCreateDisk.php
src/Snapshot.php
src/SnapshotRepository.php
tests/Commands/CreateTest.php

- Updated old str_* methods to newer PHP 8 str_* methods
- Marked implicitly nullable parameters as explicitly nullable, as implicit nullability is deprecated since PHP 8.4
- Fixed a typo
- Added missing typehints wherever it made sense
- Replaced `tap()` with `defer()` in a test - `tap()` is deprecated, it is essentially an alias for `defer()`

Code health updates
